[package]
name = "apex-tux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
tokio = {version = "1", features=["time", "net", "macros", "rt-multi-thread", "sync"]}
hidapi = { version = "1", optional = true }
num_enum = "0.5"
embedded-graphics = "0.7"
# embedded-text = "0.5.0-beta.2"
bitvec = "0.22"
tinybmp = "0.3.1"
config = { version = "0.11.0", features = ["toml"] }
futures-core = "0.3"
async-stream = "0.3"
futures = "0.3"
lazy_static = "1.4.0"
linkme = "0.2"
log = "0.4"

dbus = {version = "0.9", optional = true}
dbus-tokio = { version = "0.7.4", optional = true }
mpris = {version = "2.0.0-rc2", optional = true}
ctrlc = "3.2.0"
simplelog = "0.10.0"
pin-project-lite = "0.2.7"
tauri-hotkey = { version = "0.1.2", optional = true }
itertools = "0.10.1"
num-traits = "0.2.14"
async-rwlock = "1.3.0"
serde = { version = "1.0", optional = true, features = ["derive"] }

serde_json = { version = "1.0", optional = true }
reqwest = { version = "0.11.4", optional = true, features = ["json", "brotli", "stream", "gzip", "deflate"] }
chrono = "0.4.19"
embedded-graphics-simulator = { version = "0.3.0", optional = true }
toml = "0.5.8"

[features]
default = ["dbus-support", "crypto", "usb"]
dbus-support = ["mpris", "dbus", "dbus-tokio"]
http = ["serde", "serde_json", "reqwest"]
crypto = ["http"]
simulator = ["embedded-graphics-simulator"]
usb = ["hidapi", "tauri-hotkey"]
debug = []


